create database customer_behavior;
select * from customer;

-- Q1. What is the total revenue generated by male vs. female customers?
Select gender, sum(purchase_amount) as Revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
Select
	customer_id,
    purchase_amount,
    (SELECT AVG(purchase_amount) FROM customer) AS avg_purchase_amount
from customer
Where discount_applied = 'Yes'
AND purchase_amount >= (
	Select avg(purchase_amount) from customer
);

-- Q3. Which are the top 5 products with the highest average review rating?
Select 
	item_purchased,
    Round(AVG(review_rating), 2) AS Average_product_rating
from customer
group by item_purchased
order by Average_product_rating desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.  
select
	shipping_type,
    Round(AVG(purchase_amount), 2) as Avg_purchase_amount
from customer 
where shipping_type in ('Standard', 'Express') 
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select
	subscription_status,
	Count(customer_id) AS total_customer,
    Round(AVG(purchase_amount),2) as avg_spend,
    Round(SUM(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select
	item_purchased,
    Round(  100 * SUM(Case When discount_applied = 'Yes' then 1 else 0 end)/count(*) , 2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
Select 
	case
		when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal'
	End As customer_segment,
    count(*) as Number_of_customers
from customer
group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category? 
with item_counts As (
	select
		category,
		item_purchased,
        count(customer_id) as total_orders,
        row_number() over(
			partition by category order by count(customer_id) desc
		) As item_rank
	from customer
    group by category, item_purchased
)
select
	item_rank,
    item_purchased,
    category,
    total_orders
from item_counts
where item_rank <=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select
	subscription_status, 
	count(customer_id) as repeat_buyers
from customer 
where previous_purchases >5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select
	age_group,
    sum(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc;